# Generated by Django 4.2.29 on 2026-04-20 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Как на сайте в заголовке раздела. Например: «Хвойные деревья».', max_length=200, verbose_name='Название раздела')),
                ('slug', models.SlugField(help_text='Латиница в адресе: /catalog/&lt;slug&gt;/. Заполняется автоматически из названия, при необходимости отредактируйте.', max_length=120, unique=True, verbose_name='URL-метка (slug)')),
                ('card_label', models.CharField(blank=True, help_text='Короткая подпись в сетке разделов. Если пусто — берётся полное название.', max_length=120, verbose_name='Краткое имя на карточке')),
                ('description', models.TextField(blank=True, help_text='Подзаголовок на карточке раздела. Рекомендуется 30–160 символов, без перегруза техническими деталями.', verbose_name='Краткое описание')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньше число — выше в списке категорий в админке и на сайте.', verbose_name='Порядок в списке')),
                ('cover_path', models.CharField(blank=True, help_text='Относительно папки static/, например: media/images/pitomnik-product-hvoynye.jpg. Предпочтительно WebP/JPEG, ширина не менее 1200 px для чёткости на ретина-экранах.', max_length=500, verbose_name='Путь к обложке (файл в static)')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Описание для alt у обложки')),
                ('hub_links', models.JSONField(blank=True, default=list, help_text='JSON-массив вида [{"label": "…", "slug": "…"}] для разделов-«хабов». Обычно оставьте []', verbose_name='Ссылки хаба')),
                ('legacy_paths', models.JSONField(blank=True, default=list, verbose_name='Старые пути (редиректы)')),
            ],
            options={
                'verbose_name': 'категория каталога',
                'verbose_name_plural': 'категории каталога',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Как на карточке товара: русское название и при необходимости латынь. Без лишних технических хвостов в конце — форматы задаются в блоке «Варианты».', max_length=500, verbose_name='Полное название')),
                ('slug', models.SlugField(blank=True, help_text='Генерируется из названия. Латиница, дефисы. Можно скорректировать вручную.', max_length=200, unique=True, verbose_name='URL-метка')),
                ('description', models.TextField(help_text='Текст для страницы товара. Рекомендуется 200–4000 знаков: факты, уход, зимостойкость. Минимум 20 символов (техническое ограничение), максимум 50 000.', validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(50000)], verbose_name='Описание')),
                ('cover_path', models.CharField(blank=True, help_text='Если фото уже лежит в репозитории: путь относительно static/, напр. media/images/catalog/....webp. Формат: JPEG/WebP, соотношение сторон около 4:3 или 3:2, по длинной стороне 1400–2400 px.', max_length=500, verbose_name='Главное фото (путь в static)')),
                ('cover_upload', models.ImageField(blank=True, help_text='Файл попадёт в MEDIA и будет отдан как /media/… Статические пути из поля выше имеют приоритет, если заполнены оба — используется путь в static.', null=True, upload_to='catalog/covers/%Y/%m/', verbose_name='Или загрузить главное фото')),
                ('image_alt', models.CharField(blank=True, help_text='Кратко опишите растение на фото — для доступности и SEO.', max_length=255, verbose_name='Alt для главного фото')),
                ('height_hint', models.CharField(blank=True, help_text='Например: «выберите формат ниже» или фиксированная высота, если без вариантов.', max_length=200, verbose_name='Подпись «Высота» в карточке')),
                ('frost', models.CharField(blank=True, help_text='Например: -35°C', max_length=120, verbose_name='Морозостойкость')),
                ('light', models.CharField(blank=True, help_text='Например: солнце / полутень', max_length=120, verbose_name='Освещённость')),
                ('catalog_teaser_override', models.CharField(blank=True, help_text='Если пусто — сайт сам соберёт строку из вариантов и цен.', max_length=300, verbose_name='Тизер цены (вручную)')),
                ('is_new', models.BooleanField(default=False, help_text='Для фильтра в админке и бейджа на сайте.', verbose_name='Новинка')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть позицию без удаления.', verbose_name='Показывать на сайте')),
                ('also_in_category_slugs', models.JSONField(blank=True, default=list, help_text='Список строк-slug, например ["kustarniki-gortenziya"]. Для подразделов каталога.', verbose_name='Дополнительные категории (slug)')),
                ('legacy_paths', models.JSONField(blank=True, default=list, verbose_name='Старые URL (редиректы)')),
                ('specs_json', models.JSONField(blank=True, default=dict, help_text='Плоский объект {"Высота": "до 6 м", "Семейство": "…"}. Дублирует удобство экспорта; в админке удобнее заполнять строки в блоке «Характеристики» ниже — они синхронизируются при сохранении.', verbose_name='Характеристики (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='pages.catalogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'растение',
                'verbose_name_plural': 'растения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, help_text='Например: h 60-90', max_length=120, verbose_name='Высота / размер')),
                ('container', models.CharField(blank=True, help_text='Например: С3, Р9, Ком+Сетка', max_length=200, verbose_name='Контейнер / формат')),
                ('price', models.CharField(blank=True, help_text='Как на сайте, с «₽», напр. «1 590 ₽» или «от 18 000 ₽».', max_length=80, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pages.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'вариант (цена/формат)',
                'verbose_name_plural': 'варианты (цены/форматы)',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PlantGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/gallery/%Y/%m/', verbose_name='Файл')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Подпись (alt)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'фото галереи',
                'verbose_name_plural': 'галерея изображений',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PlantCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например: «Зимостойкость», «Скорость роста».', max_length=120, verbose_name='Название')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='pages.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики (таблица)',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
