# Generated by Django 4.2.29 on 2026-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_catalog_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cover_upload',
            field=models.ImageField(blank=True, help_text='Файл сохранится в MEDIA (URL вида /media/…). Формат: WebP или JPEG. Соотношение сторон около 4:3 или 3:2, по длинной стороне 1400–2400 px.', null=True, upload_to='catalog/covers/%Y/%m/', verbose_name='Загрузить главное фото'),
        ),
    ]
