# Generated by Django 4.2.29 on 2026-04-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_plant_cover_upload_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Название подраздела')),
                ('slug', models.SlugField(help_text='Уникально во всём каталоге (не должен совпадать с другим разделом или карточкой растения): /catalog/&lt;slug&gt;/.', max_length=120, unique=True, verbose_name='URL-метка (slug)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='В боковом меню и в админке: меньше — выше.', verbose_name='Порядок в списке')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pages.catalogcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'подкатегория каталога',
                'verbose_name_plural': 'подкатегории каталога',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
