# Generated by Django 4.2.29 on 2026-04-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_catalog_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCalendarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug (URL)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в списке')),
            ],
            options={
                'verbose_name': 'календарь: категория растений',
                'verbose_name_plural': 'календарь: категории растений',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CareCalendarPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название (рус.)')),
                ('latin', models.CharField(blank=True, max_length=500, verbose_name='Название (лат.)')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug (URL)')),
                ('varieties_json', models.JSONField(blank=True, default=list, help_text='Например: ["French Bolero", "Snow White"]. Пустой список [] — если не нужно.', verbose_name='Сорта / формы (JSON-массив строк)')),
                ('description', models.TextField(blank=True, help_text='Текст под заголовком на карточке (необязательно).', verbose_name='Краткое описание')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньше — выше внутри категории.', verbose_name='Порядок в списках')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('show_paid_service_cta', models.BooleanField(default=False, help_text='Показывать на странице растения кнопку заказа выезда специалиста (модальное окно).', verbose_name='Блок «Платная услуга» и форма выезда')),
                ('yonote_id', models.CharField(blank=True, max_length=80, verbose_name='ID Yonote (архив)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Отметьте одну или несколько. Основная категория добавится автоматически при сохранении.', related_name='calendar_plants', to='pages.carecalendarcategory', verbose_name='Все категории')),
                ('primary_category', models.ForeignKey(help_text='Используется в адресе страницы: …/calendar/&lt;категория&gt;/&lt;растение&gt;/', on_delete=django.db.models.deletion.PROTECT, related_name='plants_by_primary', to='pages.carecalendarcategory', verbose_name='Основная категория (для URL)')),
            ],
            options={
                'verbose_name': 'календарь: растение',
                'verbose_name_plural': 'календарь: растения',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareCalendarSeasonRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима')], max_length=16, verbose_name='Сезон')),
                ('body', models.TextField(verbose_name='Текст рекомендаций')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок внутри сезона')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_recommendations', to='pages.carecalendarplant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'календарь: рекомендация по сезону',
                'verbose_name_plural': 'календарь: рекомендации по сезонам',
                'ordering': ['season', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CareCalendarPlantGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='care_calendar/gallery/%Y/%m/', verbose_name='Файл')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Подпись (alt)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.carecalendarplant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'календарь: фото галереи',
                'verbose_name_plural': 'календарь: галерея',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CareCalendarPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в графике')),
                ('date_label', models.CharField(help_text='Как на сайте: «20 апреля», «15 – 25 мая» и т.п.', max_length=240, verbose_name='Дата / период (подпись)')),
                ('theme', models.CharField(blank=True, max_length=300, verbose_name='Тема работ')),
                ('content_text', models.TextField(blank=True, verbose_name='Текст (plain)')),
                ('content_html', models.TextField(blank=True, verbose_name='HTML (если заполнен — приоритетнее текста)')),
                ('images_json', models.JSONField(blank=True, default=list, help_text='Например: ["https://…/a.jpg"]. Для загрузки своих файлов используйте блок «Галерея растения».', verbose_name='Ссылки на изображения (JSON-массив URL)')),
                ('products_json', models.JSONField(blank=True, default=list, verbose_name='Рекомендуемые препараты (JSON-массив строк)')),
                ('videos_json', models.JSONField(blank=True, default=list, verbose_name='Видео (JSON-массив объектов {"label":"…","url":"…"})')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='pages.carecalendarplant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'календарь: срок в графике',
                'verbose_name_plural': 'календарь: график ухода (сроки)',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
