# Generated by Django 4.2.29 on 2026-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_care_calendar_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='carecalendarperiod',
            name='period_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='care_calendar/periods/%Y/%m/', verbose_name='Фото 1 (файл)'),
        ),
        migrations.AddField(
            model_name='carecalendarperiod',
            name='period_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='care_calendar/periods/%Y/%m/', verbose_name='Фото 2 (файл)'),
        ),
        migrations.AddField(
            model_name='carecalendarperiod',
            name='period_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='care_calendar/periods/%Y/%m/', verbose_name='Фото 3 (файл)'),
        ),
        migrations.AddField(
            model_name='carecalendarperiod',
            name='period_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='care_calendar/periods/%Y/%m/', verbose_name='Фото 4 (файл)'),
        ),
        migrations.AddField(
            model_name='carecalendarperiod',
            name='period_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='care_calendar/periods/%Y/%m/', verbose_name='Фото 5 (файл)'),
        ),
        migrations.AddField(
            model_name='carecalendarperiod',
            name='period_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='care_calendar/periods/%Y/%m/', verbose_name='Фото 6 (файл)'),
        ),
        migrations.AlterField(
            model_name='carecalendarperiod',
            name='images_json',
            field=models.JSONField(blank=True, default=list, help_text='Опционально: внешние URL, напр. ["https://…/a.jpg"]. На сайте показываются после загруженных файлов.', verbose_name='Доп. ссылки на изображения (JSON-массив URL)'),
        ),
    ]
