# Generated by Django 4.2.30 on 2026-06-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_normalize_calendar_dashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Название вкладки')),
                ('note', models.CharField(blank=True, help_text='Короткое пояснение, напр. «Новосибирск, собственный питомник».', max_length=300, verbose_name='Подпись под вкладкой')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'предзаказ: группа (вкладка)',
                'verbose_name_plural': 'предзаказ: группы (вкладки)',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PreorderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Осенняя посадка 2026', max_length=200, verbose_name='Плашка над заголовком')),
                ('hero_title', models.CharField(default='Открыт предзаказ растений на осень 2026', max_length=300, verbose_name='Заголовок (H1)')),
                ('hero_subtitle', models.CharField(default='Забронируйте нужные растения заранее. Количество ограничено.', max_length=400, verbose_name='Подзаголовок')),
                ('hero_cta', models.CharField(default='Оставить заявку', max_length=80, verbose_name='Кнопка в первом экране')),
                ('info_title', models.CharField(default='Как работает предзаказ', max_length=300, verbose_name='Заголовок информационного блока')),
                ('info_json', models.JSONField(blank=True, default=list, help_text='Иконки подставляются автоматически по порядку.', verbose_name='Пункты информационного блока (JSON-массив объектов {"title":"…","text":"…"})')),
                ('catalog_title', models.CharField(default='Доступные растения', max_length=300, verbose_name='Заголовок каталога')),
                ('catalog_subtitle', models.CharField(blank=True, default='Отметьте нужные позиции — они автоматически попадут в заявку.', max_length=400, verbose_name='Подзаголовок каталога')),
                ('form_title', models.CharField(default='Забронировать растения', max_length=200, verbose_name='Заголовок формы')),
                ('form_subtitle', models.CharField(blank=True, default='Менеджер свяжется для подтверждения заказа в течение рабочего дня.', max_length=400, verbose_name='Подзаголовок формы')),
                ('form_submit', models.CharField(default='Забронировать растения', max_length=80, verbose_name='Кнопка отправки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'предзаказ: тексты лендинга',
                'verbose_name_plural': 'предзаказ: тексты лендинга',
            },
        ),
        migrations.CreateModel(
            name='PreorderPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('size', models.CharField(blank=True, help_text='Напр.: «ком+сетка, H 1,5-2 м».', max_length=200, verbose_name='Размер / формат')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Цена по предзаказу за штуку. Пусто — цена не показывается («по запросу»).', null=True, verbose_name='Цена, ₽')),
                ('image_path', models.CharField(blank=True, help_text='Если фото уже в репозитории: путь относительно static/, напр. media/images/catalog/migrated/....webp', max_length=500, verbose_name='Фото (путь в static)')),
                ('image_upload', models.ImageField(blank=True, help_text='Файл сохранится в MEDIA. Имеет приоритет над «Фото (путь в static)».', null=True, upload_to='preorder/%Y/%m/', verbose_name='Загрузить фото')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt для фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='pages.preordergroup', verbose_name='Группа (вкладка)')),
            ],
            options={
                'verbose_name': 'предзаказ: растение',
                'verbose_name_plural': 'предзаказ: растения',
                'ordering': ['group__sort_order', 'sort_order', 'pk'],
            },
        ),
    ]
