# Generated by Django 4.2.30 on 2026-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_predzakaz_derevya_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Раздел пропадает из меню каталога (например, сезонная рассада вне сезона). Прямые ссылки на раздел и его товары продолжают работать.', verbose_name='Скрыть с сайта'),
        ),
    ]
