# Generated by Django 4.2.30 on 2026-08-23 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_catalogcategory_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Адрес статьи: /stati/<метка>/. Латиница, дефисы.', max_length=200, unique=True, verbose_name='URL-метка')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('excerpt', models.TextField(help_text='Короткое описание для карточки в списке и для meta description по умолчанию.', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Аннотация')),
                ('lead', models.TextField(blank=True, verbose_name='Лид (первый абзац)')),
                ('sections', models.JSONField(blank=True, default=list, help_text='Список объектов: heading, paragraphs[], steps[], list[], table{headers,rows}.', verbose_name='Разделы статьи')),
                ('faq', models.JSONField(blank=True, default=list, help_text='Список объектов {q, a}. Идёт в FAQPage JSON-LD.', verbose_name='FAQ')),
                ('seo_title', models.CharField(blank=True, max_length=300, verbose_name='SEO-заголовок (title)')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='Meta description')),
                ('image_upload', models.ImageField(blank=True, help_text='Файл сохранится в MEDIA. Имеет приоритет над «Обложка (путь в static)».', null=True, upload_to='articles/%Y/%m/', verbose_name='Обложка (загруженный файл)')),
                ('image_path', models.CharField(blank=True, help_text='Например media/images/gazon-b2b-courtyard.jpg (без ведущего /static/).', max_length=300, verbose_name='Обложка (путь в static)')),
                ('image_alt', models.CharField(blank=True, max_length=300, verbose_name='Alt для обложки')),
                ('status', models.CharField(choices=[('draft', 'Черновик (виден только по preview-ссылке)'), ('scheduled', 'Запланирована (выйдет в дату публикации)'), ('published', 'Опубликована (видна сразу)')], default='draft', max_length=20, verbose_name='Статус')),
                ('date_published', models.DateField(help_text='Для статуса «Запланирована» статья появится на сайте в эту дату.', verbose_name='Дата публикации')),
                ('date_modified', models.DateField(blank=True, null=True, verbose_name='Дата обновления')),
                ('source', models.CharField(blank=True, help_text='Кто загрузил: api, admin, имя оператора.', max_length=100, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи (/stati/)',
                'ordering': ['-date_published', '-pk'],
            },
        ),
    ]
