# Generated by Django 4.2.30 on 2026-09-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='lead_id')),
                ('landing_id', models.CharField(db_index=True, max_length=100, verbose_name='Посадочная')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Нормализован к 7XXXXXXXXXX.', max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('service_label', models.CharField(blank=True, max_length=200, verbose_name='Услуга')),
                ('area_label', models.CharField(blank=True, max_length=100, verbose_name='Объём')),
                ('landing_url', models.URLField(blank=True, max_length=500, verbose_name='Адрес страницы')),
                ('page_path', models.CharField(blank=True, max_length=300, verbose_name='Путь страницы')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Referrer')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=300, verbose_name='utm_campaign')),
                ('utm_content', models.CharField(blank=True, max_length=300, verbose_name='utm_content')),
                ('utm_term', models.CharField(blank=True, max_length=300, verbose_name='utm_term')),
                ('yclid', models.CharField(blank=True, max_length=100, verbose_name='yclid')),
                ('b24_lead_id', models.IntegerField(blank=True, null=True, verbose_name='ID лида в Б24')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'заявка с посадочной',
                'verbose_name_plural': 'заявки с посадочных',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
