# Generated by Django 4.2.30 on 2026-09-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_landinglead'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Часть URL: /opt/<раздел>/<слаг>/. Менять после запуска рекламы нельзя.', max_length=250, verbose_name='Слаг')),
                ('size', models.CharField(blank=True, help_text='Высота, объём кома или контейнер - как принято в плане продаж.', max_length=200, verbose_name='Размер')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Цена за единицу. Единственный источник цены: из браузера цену не берём.', max_digits=10, verbose_name='Оптовая цена, ₽')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица')),
                ('short_description', models.TextField(blank=True, help_text='Что это, для кого партия, условия отгрузки. Без розничного сторителлинга.', verbose_name='Кратко о позиции')),
                ('image', models.ImageField(blank=True, help_text='Только реальное актуальное фото товара, который отгружаем сейчас.', upload_to='wholesale/', verbose_name='Фото')),
                ('availability', models.CharField(blank=True, help_text='Например: «в наличии 120 шт» или «под заказ, отгрузка 5 дней».', max_length=200, verbose_name='Наличие')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Позиция, которую двигаем в первую очередь: поднимается в списке.', verbose_name='Акцент')),
                ('sort_order', models.IntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_demo', models.BooleanField(default=False, help_text='Заглушка каркаса: название, размер и цена выдуманы. Снять после заливки плана.', verbose_name='Демо-данные')),
            ],
            options={
                'verbose_name': 'позиция оптового каталога',
                'verbose_name_plural': 'оптовый каталог: позиции',
                'ordering': ['-is_highlighted', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='order_id')),
                ('name', models.CharField(max_length=200, verbose_name='Имя / компания')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('phone', models.CharField(help_text='Нормализован к 7XXXXXXXXXX.', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма без скидки, ₽')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Скидка, %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка, ₽')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого, ₽')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Всего единиц')),
                ('discount_basis', models.CharField(blank=True, max_length=20, verbose_name='База скидки')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('page_path', models.CharField(blank=True, max_length=300, verbose_name='Путь страницы')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Referrer')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=300, verbose_name='utm_campaign')),
                ('utm_content', models.CharField(blank=True, max_length=300, verbose_name='utm_content')),
                ('utm_term', models.CharField(blank=True, max_length=300, verbose_name='utm_term')),
                ('yclid', models.CharField(blank=True, max_length=100, verbose_name='yclid')),
                ('b24_lead_id', models.IntegerField(blank=True, null=True, verbose_name='ID лида в Б24')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'оптовый заказ',
                'verbose_name_plural': 'оптовый каталог: заказы',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Часть URL: /opt/<слаг>/. Менять после запуска рекламы нельзя.', max_length=200, unique=True, verbose_name='Слаг')),
                ('intro', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('sort_order', models.IntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_demo', models.BooleanField(default=False, help_text='Заглушка каркаса. Снять после заливки реального плана продаж.', verbose_name='Демо-данные')),
            ],
            options={
                'verbose_name': 'раздел оптового каталога',
                'verbose_name_plural': 'оптовый каталог: разделы',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('size', models.CharField(blank=True, max_length=200, verbose_name='Размер')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу, ₽')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма строки, ₽')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='pages.wholesaleitem', verbose_name='Позиция')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pages.wholesaleorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'строка оптового заказа',
                'verbose_name_plural': 'строки оптового заказа',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='wholesaleitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.wholesalesection', verbose_name='Раздел'),
        ),
        migrations.AlterUniqueTogether(
            name='wholesaleitem',
            unique_together={('section', 'slug')},
        ),
    ]
