# Generated by Django 4.2.30 on 2026-09-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_wholesaleitem_wholesaleorder_wholesalesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleorderline',
            name='variant_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='wholesaleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена за единицу без скидки. От неё считаются все оптовые ступени по сетке из pages/wholesale_pricing.py - отдельных полей под ступени нет. Единственный источник цены: из браузера цену не берём.', max_digits=10, verbose_name='Розничная цена (без скидки), ₽'),
        ),
        migrations.CreateModel(
            name='WholesaleItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: «Синий цвет», «Ком 60 см», «Партия из теплицы №2».', max_length=200, verbose_name='Название варианта')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Сколько единиц этого варианта можно отгрузить. 0 - вариант не заказать.', verbose_name='Остаток')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Пусто - берём цену позиции. Заполнять только если вариант дороже или дешевле.', max_digits=10, null=True, verbose_name='Своя розничная цена, ₽')),
                ('image', models.ImageField(blank=True, help_text='Пусто - показываем фото позиции.', upload_to='wholesale/', verbose_name='Фото варианта')),
                ('sort_order', models.IntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pages.wholesaleitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'вариант позиции',
                'verbose_name_plural': 'оптовый каталог: варианты позиций',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='wholesaleorderline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='pages.wholesaleitemvariant', verbose_name='Вариант'),
        ),
    ]
