# Generated by Django 4.2.30 on 2026-09-10 10:10

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_wholesaleorderline_variant_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Обложка-запаска. Если у позиции есть галерея, обложкой становится её первый снимок, а это поле остаётся про запас.', upload_to='wholesale/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='WholesaleItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Живое фото товара, который отгружаем сейчас. Лучше webp.', upload_to=pages.models.wholesale_photo_path, verbose_name='Снимок')),
                ('caption', models.CharField(blank=True, help_text='Необязательно: что именно на кадре («ком», «крона», «лист»).', max_length=200, verbose_name='Подпись')),
                ('source_name', models.CharField(blank=True, help_text='Заполняет команда import_wholesale_photos. По нему повторный прогон понимает, что снимок уже залит, и не плодит дубли. Руками не трогать.', max_length=255, verbose_name='Имя исходного файла')),
                ('sort_order', models.IntegerField(default=100, help_text='Первый снимок по порядку становится обложкой позиции.', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.wholesaleitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'фото позиции',
                'verbose_name_plural': 'оптовый каталог: фото позиций',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
