# Generated by Django 4.2.30 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_wholesaleitem_image_wholesaleitemphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleorder',
            name='discount_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Деревья и остальное считаются независимо: у каждой группы своя ступень.', verbose_name='Скидка по группам'),
        ),
    ]
