# Generated by Django 4.2.30 on 2026-09-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_wholesaleorder_discount_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinglead',
            name='metrika_uploaded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Отправлена в Метрику'),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='metrika_uploaded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Отправлен в Метрику'),
        ),
    ]
