# Generated by Django 4.2.30 on 2026-10-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_landinglead_metrika_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='seo_intro',
            field=models.TextField(blank=True, default='', help_text='SEO-текст под заголовком, 150-220 слов, допускается простой HTML (p, a, strong)', verbose_name='SEO-интро под заголовком'),
        ),
        migrations.AddField(
            model_name='catalogsubcategory',
            name='seo_intro',
            field=models.TextField(blank=True, default='', help_text='SEO-текст под заголовком, 150-220 слов, допускается простой HTML (p, a, strong)', verbose_name='SEO-интро под заголовком'),
        ),
    ]
