# Generated by Django 4.2.30 on 2026-05-18 12:17

import care_notifications.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=care_notifications.models._generate_token, help_text='Подписывает ссылки /care/manage/?t=... и opt-in deep-links ботов.', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('max', 'MAX')], default='email', max_length=16)),
                ('groups', models.JSONField(default=list, help_text="slug'и групп из pages.data.CARE_SUBSCRIPTION_GROUPS, например ['seasonal','roses'].")),
                ('promo_subscribed', models.BooleanField(default=False, help_text='Согласие на новинки и акции (объединённая опция promo в форме).')),
                ('source', models.CharField(choices=[('purchase', 'После покупки'), ('web', 'С сайта'), ('ads', 'С рекламы Службы заботы'), ('unknown', 'Источник не определён')], default='unknown', max_length=16)),
                ('page_path', models.CharField(blank=True, max_length=512)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('b24_lead_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('b24_contact_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('max_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('max_opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подписка на Службу заботы',
                'verbose_name_plural': 'Подписки на Службу заботы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigestDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('max', 'MAX')], max_length=16)),
                ('week_key', models.CharField(help_text='ISO неделя выпуска, например 2026-W21. Идемпотентность дайджеста.', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, help_text='ID сообщения у провайдера (Unisender message_id, TG message_id и т.д.).', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='care_notifications.caresubscription')),
            ],
            options={
                'verbose_name': 'Доставка дайджеста',
                'verbose_name_plural': 'Доставки дайджестов',
                'ordering': ['-created_at'],
                'unique_together': {('subscription', 'channel', 'week_key')},
            },
        ),
    ]
