# Generated by Django 4.2.30 on 2026-06-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneCCardSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, help_text='Канонический +7XXXXXXXXXX - идентификатор карты в 1С.', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('b24_contact_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='ID контакта в Б24 для сверки (карта пишется и туда, и в 1С).', null=True)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка (исчерпаны попытки)')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Отправка карты в 1С',
                'verbose_name_plural': 'Отправки карт в 1С',
                'ordering': ['-created_at'],
            },
        ),
    ]
