# Generated by Django 4.2.30 on 2026-07-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_notifications', '0002_oneccardsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_key', models.CharField(db_index=True, help_text='ISO неделя, например 2026-W28. Один промо на неделю.', max_length=16, unique=True)),
                ('status', models.CharField(choices=[('awaiting_content', 'Ждём контент'), ('review', 'На согласовании'), ('confirmed', 'Подтверждено'), ('sent', 'Разослано'), ('cancelled', 'Отменено')], db_index=True, default='awaiting_content', max_length=16)),
                ('text', models.TextField(blank=True, help_text='Текст акции от специалиста.')),
                ('image', models.ImageField(blank=True, help_text='Присланная картинка акции. Даёт публичный URL для всех каналов.', upload_to='care_promo/')),
                ('tg_file_id', models.CharField(blank=True, help_text='Telegram file_id исходной картинки (подстраховка, если скачать не удалось).', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Промо-акция недели',
                'verbose_name_plural': 'Промо-акции недели',
                'ordering': ['-week_key'],
            },
        ),
    ]
